---
- name: Install required packages
  become: yes
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add docker's official GPG key to apt
  become: true
  apt_key:
    url: "{{ docker_key_url }}"
    state: present

- name: Add Docker's apt repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install docker CE
  become: true
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - "docker-ce"
    - "docker-ce-cli"
    - "containerd.io"

- name: Add user to docker group
  become: true
  user:
    name: "{{ item }}"
    groups: "docker"
  with_items: "{{ docker_users }}"

- name: Install latest version of docker-compose
  shell: "curl -L https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose"
  when: docker_compose

- name: Make docker-compose executable
  shell: "chmod +x /usr/local/bin/docker-compose"
  when: docker_compose
